baseURL = 'https://taubyte.github.io/blog/'
languageCode = 'en-us'
title = 'Taubyte Blog'
theme = 'PaperMod'

[params]
# Theme-specific parameters
env = "production"
title = "Taubyte Blog"
description = "A modern blog built with Hugo and PaperMod theme"
keywords = ["Blog", "PaperMod", "Hugo"]
author = "Your Name"
images = ["<link or path of image for opengraph, twitter-cards>"]
DateFormat = "January 2, 2006"
defaultTheme = "auto" # dark, light
disableThemeToggle = false

ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

[params.assets]
# disableHLJS = true # to disable highlight.js
# disableFingerprinting = true
favicon = "<link / abs url>"
favicon16x16 = "<link / abs url>"
favicon32x32 = "<link / abs url>"
apple_touch_icon = "<link / abs url>"
safari_pinned_tab = "<link / abs url>"

[params.label]
text = "Taubyte Blog"
icon = "/apple-touch-icon.png"
iconHeight = 35

# profile-mode
[params.profileMode]
enabled = false # needs to be explicitly set
title = "ExampleSite"
subtitle = "This is subtitle"
imageUrl = "<title or url>"
imageWidth = 120
imageHeight = 120
imageTitle = "my image"

[[params.profileMode.buttons]]
name = "Posts"
url = "/posts"

[[params.profileMode.buttons]]
name = "Tags"
url = "/tags"

# home-info mode
[params.homeInfoParams]
Title = "Hi there 👋"
Content = "Welcome to my blog"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/"

[[params.socialIcons]]
name = "stackoverflow"
url = "https://stackoverflow.com"

[[params.socialIcons]]
name = "github"
url = "https://github.com/"

[params.analytics.google]
SiteVerificationTag = "XYZabc"

[params.analytics.bing]
SiteVerificationTag = "XYZabc"

[params.analytics.yandex]
SiteVerificationTag = "XYZabc"

[params.cover]
hidden = true # hide everywhere but not in structured data
hiddenInList = true # hide on list pages and home
hiddenInSingle = true # hide on single page

[params.editPost]
URL = "https://github.com/<path_to_repo>/content"
Text = "Suggest Changes" # edit text
appendFilePath = true # to append file path to Edit link

# for search
# https://fusejs.io/api/options.html
[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1000
threshold = 0.4
minMatchCharLength = 0
keys = ["title", "permalink", "summary", "content"]

[menu]
[[menu.main]]
identifier = "categories"
name = "Categories"
url = "/categories/"
weight = 10

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 20

[[menu.main]]
identifier = "example"
name = "Example.org"
url = "https://example.org"
weight = 30

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses = true
[markup.highlight]
noClasses = false
# anchorLineNos = true
# codeFences = true
# guessSyntax = true
# lineNos = true
# style = "github"
